---
title: "01_Initialization"
author: "ML"
date: "8/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Set your working directory
The directory we start from with knitr:
```{r initialization, include=FALSE, echo=FALSE}
rm(list = ls())
```
  
# Load libraries

```{r download packages if needed, include=FALSE}

library(tidyverse)
#library(reshape2)
library(readxl)
library(readr)

library(ggplot2)
library(patchwork)
library(grid)
library(gridExtra)
library(ggExtra)
library(ggthemes)
library(ggside)
#library(ggpubr)
#library(sjPlot)

#install.packages("coda")
#install.packages("rjags") -> vergt eerst aparte installatie
#install.packages("BEST")
library(coda)
#library(rjags)
#library(BEST)

#

library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

library(tidybayes)
library(bayesplot)
options(mc.cores = parallel::detectCores())
library(brms)

#library(shinystan)
library(bayestestR)
library(posterior)

#library(lme4)
#library(BListener)
#library(flexdashboard)

##library(sjPlot)
#library(kableExtra)
#library(magick)

#library(modelbased)
#library(emmeans)
#library(patchwork)

#install.packages("easystats", repos = "https://easystats.r-universe.dev")
#library("easystats")
#library(insight)
#library(see)
#library(equatiomatic)
library(performance)
library(parameters)
#library(see)

library(mgcv)
#library(smoothr)
library(gratia)


library(foreach)
library(doParallel)

#library(DescTools)
#install.packages("ggcorrplot")                      # Install ggcorrplot package
library("ggcorrplot") 


#remotes::install_github("stan-dev/cmdstanr")
library(cmdstanr)
check_cmdstan_toolchain(fix = TRUE, quiet = TRUE)
check_cmdstan_toolchain()
#install_cmdstan(cores = 16, overwrite=TRUE)
cmdstan_path()

library(xfun)

#library(misty)
#library(rstatix)
#library(coin)
#library(tidymv)
#library(flextable)
#library(broom.mixed)
```
