---
title: "02_functions"
author: "ML"
date: "2022-08-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Modelling functions GUSO paper
```{r modellingfunctions, eval=FALSE, include=FALSE}
load(file = "Data.RData")

#############
# Modelling longitudinal model
############### 
run_model_cmdstanr <- function(Data, form, fam, priors){
  print(paste(form[1],fam,sep="\n"))
  fit <- brm(data = Data,
             formula = form,
             family = fam,
             prior = priors,
             iter = 4000, warmup = 1000,
             control = list(adapt_delta = 0.995,  max_treedepth = 12),
             # init = 0,
             # thin = 2,
             chains = 2,
             backend = "cmdstanr",
             threads = threading(2),
             save_pars = save_pars(all = TRUE),
             #sample_prior = TRUE #,
             #file = filen
  )
  return(fit)
}

do_BF_comparison <- function(fit1,fit2){
  bf <- bayes_factor(fit1,fit2,log=TRUE)
  return(bf)
}

do_post_analysis <- function(fit){
  # fit <- model_procustus0M
  library(patchwork)
  t <- fit$formula
  print(t)
  p <- pp_check(fit, ndraws = 50)
  m <- mcmc_plot(fit, regex = TRUE, variable = "^[bs]_")
  #ce <- plot(conditional_effects(fit, re_formula = NA), ask = FALSE)[[1]]
  #sd <- fit %>% spread_draws(`r_condition:trial`[A,Intercept]) %>% 
  #  ggplot(aes(`r_condition:trial`,A)) + stat_halfeye()
  p01 <- (p + m) #/ (ce + sd)
  print(p01)
  #s <- summary(fit) 
  b <- r2_bayes(fit) %>% 
    data.frame() %>% 
    mutate(across(where(is.numeric), round, 2))
  print(b)
  print("calculating parameters... can take some time")
  par <- parameters(fit, test = c("pd","bf"),effects = "all",centrality = "mean") %>% 
    data.frame() %>% 
    mutate(across(where(is.numeric), round, 2))
  print(par)
#  return(list(p,m,ce,sd,b,par))
  return(list(t,p01,b,par))
}

do_hypothesis_test <- function(fit){
  # Contrast condition2 condition1
  h1 <- hypothesis(fit,c("b_condition1 < b_condition2") ,class = NULL)$hypothesis
  t1 <- "c12"
  # contrast trials
  #Condition1
  h2 <- hypothesis(fit,c("r_condition:trial[1_1,Intercept] > r_condition:trial[1_2,Intercept]") ,class = NULL)$hypothesis
  t2 <- "c1t12"
  h3 <- hypothesis(fit,c("r_condition:trial[1_1,Intercept] > r_condition:trial[1_3,Intercept]") ,class = NULL)$hypothesis
  t3 <- "c1t13"
  h4 <- hypothesis(fit,c("r_condition:trial[1_1,Intercept] > r_condition:trial[1_4,Intercept]") ,class = NULL)$hypothesis
    t4 <- "c1t14"
  h5 <- hypothesis(fit,c("r_condition:trial[1_2,Intercept] > r_condition:trial[1_3,Intercept]") ,class = NULL)$hypothesis
    t5 <- "c1t23"
  h6 <- hypothesis(fit,c("r_condition:trial[1_2,Intercept] > r_condition:trial[1_4,Intercept]") ,class = NULL)$hypothesis
    t6 <- "c1t24"
  h7 <- hypothesis(fit,c("r_condition:trial[1_3,Intercept] > r_condition:trial[1_4,Intercept]") ,class = NULL)$hypothesis
    t7 <- "c1t34"
    
  #Condition2
  h8 <- hypothesis(fit,c("r_condition:trial[2_1,Intercept] > r_condition:trial[2_2,Intercept]") ,class = NULL)$hypothesis
    t8 <- "c2t12"
  h9 <- hypothesis(fit,c("r_condition:trial[2_1,Intercept] > r_condition:trial[2_3,Intercept]") ,class = NULL)$hypothesis
    t9 <- "c2t13"
  h10 <- hypothesis(fit,c("r_condition:trial[2_1,Intercept] > r_condition:trial[2_4,Intercept]") ,class = NULL)$hypothesis
  t10 <- "c2t14"
  h11 <- hypothesis(fit,c("r_condition:trial[2_2,Intercept] > r_condition:trial[2_3,Intercept]") ,class = NULL)$hypothesis
  t11 <- "c2t23"
  h12 <- hypothesis(fit,c("r_condition:trial[2_2,Intercept] > r_condition:trial[2_4,Intercept]") ,class = NULL)$hypothesis
  t12 <- "c2t24"
  h13 <- hypothesis(fit,c("r_condition:trial[2_3,Intercept] > r_condition:trial[2_4,Intercept]") ,class = NULL)$hypothesis
  t13 <- "c2t34"
  
  #Condition12
  h14 <- hypothesis(fit,c("b_condition1 + r_condition:trial[1_1,Intercept] > b_condition2 + r_condition:trial[2_1,Intercept]") ,class = NULL)$hypothesis
  t14 <- "c12t1"
  h15 <- hypothesis(fit,c("b_condition1 + r_condition:trial[1_2,Intercept] > b_condition2 + r_condition:trial[2_2,Intercept]") ,class = NULL)$hypothesis
  t15 <- "c12t2"
  h16 <- hypothesis(fit,c("b_condition1 + r_condition:trial[1_3,Intercept] > b_condition2 + r_condition:trial[2_3,Intercept]") ,class = NULL)$hypothesis
  t16 <- "c12t3"
  h17 <- hypothesis(fit,c("b_condition1 + r_condition:trial[1_4,Intercept] > b_condition2 + r_condition:trial[2_4,Intercept]") ,class = NULL)$hypothesis
  t17 <- "c12t4"
    
  h <- rbind(h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11,h12,h13,h14,h15,h16,h17) %>% data.frame() %>% mutate(across(where(is.numeric), round, 2))
  t <- rbind(t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17) %>% data.frame()
  names(t) <- "Label"
  t <- t %>% mutate(Label = factor(Label,labels = Label, levels = Label) )
  
  h <- cbind(h,t) %>% mutate(Tag =  paste(Estimate,"[",CI.Lower,",", CI.Upper, "] --", Post.Prob, Star ) ) 
  
  # to print
  hh <- h %>% select(Hypothesis,Label,Estimate,CI.Lower,CI.Upper,Post.Prob,Star)
  
  p1 <- h %>% ggplot() +
  geom_errorbarh(aes(xmin=CI.Lower,xmax=CI.Upper,y=Label) ) +
  geom_point(aes(x=Estimate,y=Label)) +
#  geom_text(aes(x=.85,label=(tag), y=rowname),size=3) +
  #xlim(-.25,1) +
  theme_bw() +
  ylab("Contrasts") +
  xlab("Posterior distribution (median, ci-95%)")

  p2 <- h %>% ggplot()+
 # geom_errorbarh(aes(xmin=lowerCI95,xmax=upperCI95,y=rowname) ) +
  # geom_point(aes(x=median,y=rowname)) +
  geom_text(aes(x=.85,label=Tag, y=Label),size=3) +
  #xlim(-.25,1) +
  theme_void() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        )
p <- (p1 + p2)
  
  return(list(hh,p))
}

do_comparison <- function(fit1,fit2){
  bf <- bayes_factor(fit1,fit2)
  l <- loo(fit1,fit2)
  return(list(bf,l))
}

do_post_analysis_Multi <- function(fit) {
  t <- fit$formula
    m <- mcmc_plot(fit, regex = TRUE, variable = "^b_")
  #ce <- plot(conditional_effects(fit, re_formula = NA), ask = FALSE)[[1]]
  #  p1 <- pp_check(fit, ndraws = 50,resp = "WPQ")
  #  p2 <- pp_check(fit, ndraws = 50,resp = "MPQS")
  #  p3  <- pp_check(fit, ndraws = 50,resp = "MPQP")

  # sd1 <- fit %>% spread_draws(`r_condition:trial__WPQ`[A,Intercept]) %>% 
  #    ggplot(aes(`r_condition:trial__WPQ`,A)) + stat_halfeye()
  # sd2 <- fit %>% spread_draws(`r_condition:trial__MPQS`[A,Intercept]) %>% 
  #   ggplot(aes(`r_condition:trial__MPQS`,A)) + stat_halfeye()
  # sd3 <- fit %>% spread_draws(`r_condition:trial__MPQP`[A,Intercept]) %>% 
  #   ggplot(aes(`r_condition:trial__MPQP`,A)) + stat_halfeye()
  # 
  #p01 <- (m + p1) / (p2 + p3)
  #s <- summary(fit) 
  bb <- r2_bayes(fit)
  b<- head(bb) %>% data.frame %>%  mutate(across(where(is.numeric), round, 2))
  #print(b)
  par <- parameters(fit, test = c("pd"), effects = "all",centrality = "mean") %>% 
    data.frame() %>% 
    mutate(across(where(is.numeric), round, 2))
return = list(m, b, par)
}
```


# do_calc is the basis routine for processing all data.

```{r}
do_calc <- function(Data1, metricsStr, Legende,prefix){
  print(paste("do_calc processing of: ",metricsStr))
  print(paste(metricsStr))
  # ############
  # 2.process metricsCol
  # ############
  foreach (i = 1:length(metricsStr))  %dopar% { 
    # c = "V8"
    # i = 1
    str0 = metricsStr[i]
    print(paste("co_calc processing of: ...", str0))
    # Compose data
    D <- Data1 %>% rename(feature = str0)
    D_11 <- D %>% filter(violin == "1",piece == "1") %>% select ( !matches("V[123456789]") )
    D_12 <- D %>% filter(violin == "1",piece == "2") %>% select ( !matches("V[123456789]") )
    D_21 <- D %>% filter(violin == "2",piece == "1") %>% select ( !matches("V[123456789]") )
    D_22 <- D %>% filter(violin == "2",piece == "2") %>% select ( !matches("V[123456789]") )
    print("Process 11")
    R_11 <- do_gam(D_11) # returns a list of G,D,P0,P1
    print("Process 12")
    R_12 <- do_gam(D_12) 
    print("Process 21")
    R_21 <- do_gam(D_21) 
    print("Process 22")
    R_22 <- do_gam(D_22) 
    print("Creating titles for plots")
    titleStr_11 <- paste(str0,  Legende$metric[Legende$columncode==str0], "_11", sep="")
    titleStr_12 <- paste(str0,  Legende$metric[Legende$columncode==str0], "_12", sep="")
    titleStr_21 <- paste(str0,  Legende$metric[Legende$columncode==str0], "_21", sep="")
    titleStr_22 <- paste(str0,  Legende$metric[Legende$columncode==str0], "_22", sep="")
    print("Creating plots")
    Plot_11 <- do_plot(R_11)[[1]] + ggtitle(titleStr_11) # + ylim(0,1)
    Plot_12 <- do_plot(R_12)[[1]] + ggtitle(titleStr_12)
    Plot_21 <- do_plot(R_21)[[1]] + ggtitle(titleStr_21)
    Plot_22 <- do_plot(R_22)[[1]] + ggtitle(titleStr_22) 
    print("Creating filenames")
    filenameR_11 = paste("Results/", prefix, str0, "_11.RData",sep="")
    filenameR_12 = paste("Results/", prefix, str0, "_12.RData",sep="")
    filenameR_21 = paste("Results/", prefix, str0, "_21.RData",sep="")
    filenameR_22 = paste("Results/", prefix, str0, "_22.RData",sep="")
    print(paste("do_calc fitted model to file..."))
    R <- R_11
    save(file = filenameR_11, R)
    R <- R_12
    save(file = filenameR_12, R)
    R <- R_21
    save(file = filenameR_21, R)
    R <- R_22
    save(file = filenameR_22, R)
    filenameR_11 = paste("Figures/", prefix, str0, "_11",sep="")
    filenameR_12 = paste("Figures/", prefix, str0, "_12",sep="")
    filenameR_21 = paste("Figures/", prefix, str0, "_21",sep="")
    filenameR_22 = paste("Figures/", prefix, str0, "_22",sep="")
    print(paste("do_calc plot to file..."))
    make_pdf_figure(filenameR_11 , Plot_11)
    make_pdf_figure(filenameR_12 , Plot_12)
    make_pdf_figure(filenameR_21 , Plot_21)
    make_pdf_figure(filenameR_22 , Plot_22)
  }
}
```

# General functions for plotting

```{r}
make_pdf_figure <- function(fn,fig){
  fn_pdf = paste(fn,".pdf",sep="")
  print(paste("plotting", fn_pdf))
  pdf(file = fn_pdf ,width=9, height=8 )  #Note that you can convert inches to centimeters dividing by 2.54.
  print(fig)
  dev.off()
}

make_png_figure <- function(fn,fig){
  fn_png = paste(fn,".png",sep="")
  print(paste("plotting", fn_png))
  png(filename=fn_png, width=7, height=3, units = "in", res = 300)
  print(fig)
  dev.off()
}

make_svg_figure <- function(fn,fig){
  fn_svg = paste(fn,".svg",sep="")
  print(paste("plotting", fn_svg))
  svg(file = fn_svg ,width=7, height=3
      #Note that you can convert inches to centimeters dividing by 2.54.
  ) 
  print(fig)
  dev.off()
}


make_eps_figure <- function(fn,fig){
  fn_eps = paste(fn,".eps",sep="")
  print(paste("plotting", fn_eps))
  postscript(file = fn_eps ,width=7, height=3
             #Note that you can convert inches to centimeters dividing by 2.54.
  ) 
  print(fig)
  dev.off()
}

make_fig <- function(fn,fig){
  make_pdf_figure(fn,fig)
  make_png_figure(fn,fig)
  make_svg_figure(fn,fig)
  make_eps_figure(fn,fig)
}

#prefix
#make_fig("prefix",p1)
```


# do_area: calculate the area of between dynamic global mean (P0 in do_gam) and dynamic specific mean (P1) in do_gam
```{r}
##########
do_area <- function(R_){
  # R_ <- R_11
  R0 <- R_[[4]] # see P0 in do_gam
  R1 <- R_[[5]] # see P1 in do_gam
  RR2 <- R1 %>% mutate(fitted0 = R0$fitted, # use dynamic group mean
                       upper0 = R0$upper,
                       lower0 = R0$lower,
                       fitted1 = R1$fitted, # use dynamic individual mean
                       upper1 = R1$upper,
                       lower1 = R1$lower,
                       fitted_area = fitted1 - fitted0, # positive values mark worse performance than group
                        upper_area = upper1 - upper0,
                       lower_area = lower1 - lower0)
  #ntimestep = length(unique(R0$timestep)) * length(unique(RR2$trial))
  tRR <- RR2 %>% group_by(participantcondition)  %>% summarize(areaM = mean(fitted_area),
                                                               areaU = mean(upper_area),
                                                               areaL = mean(lower_area),
                                                               fitted1M = mean(fitted1),
                                                               fitted1U = mean(upper1),
                                                               fitted1L = mean(lower1)) %>% ungroup() #, 
                                                               #areaScaled = scale(area),
                                                               #areaPlus = sum(areaScaled[areaScaled > 0]) / ntimestep, 
                                                               #areaMin = sum(areaScaled[areaScaled < 0])/ ntimestep,
                                                               #areaDiff = areaMin + areaPlus

  return(tRR)
}

if(0){
  RR %>% filter(participantcondition == "4.1") %>%
    ggplot()+
    geom_line(aes(x=timestep,y=fitted0),color = "blue") +
    geom_line(aes(x=timestep,y=fitted1),color="red")
  RR2 %>% 
    ggplot()+
    geom_point(aes(x=timestep,y=areaScaled,color = participantcondition),color = "blue") 
}
```



# Function to calculate contrasts 26/01/2023
Used for calculating contrasts of conditions in procustus, spark


```{r}
do_contrast <- function(fit){

#fit <- model_procustus0M_d2
#fit <- model_procustus1M_d2

s <- summary(fit)
c <- d2_coef <- coef(fit) 
#d2_ranef <- ranef(fit) 

cc <- coef(fit,summary = FALSE) %>% as.data.frame() %>% 
  mutate(
  condition.1.Intercept = condition.trial.1_1.condition1,
  condition.2.Intercept = condition.trial.1_1.condition2,

  diff_c12 = condition.1.Intercept - condition.2.Intercept, 
  diff_c12_t1 = condition.1.Intercept + condition.trial.1_1.Intercept - (condition.2.Intercept + condition.trial.2_1.Intercept),
  diff_c12_t2 = condition.1.Intercept + condition.trial.1_2.Intercept - (condition.2.Intercept + condition.trial.2_2.Intercept),
  diff_c12_t3 = condition.1.Intercept + condition.trial.1_3.Intercept - (condition.2.Intercept + condition.trial.2_3.Intercept),
  diff_c12_t4 = condition.1.Intercept + condition.trial.1_4.Intercept - (condition.2.Intercept + condition.trial.2_4.Intercept),
  
  diff_c1_t12 = condition.1.Intercept + condition.trial.1_1.Intercept - (condition.1.Intercept + condition.trial.1_2.Intercept),
  diff_c1_t13 = condition.1.Intercept + condition.trial.1_1.Intercept - (condition.1.Intercept + condition.trial.1_3.Intercept),
  diff_c1_t14 = condition.1.Intercept + condition.trial.1_1.Intercept - (condition.1.Intercept + condition.trial.1_4.Intercept),
  diff_c1_t23 = condition.1.Intercept + condition.trial.1_2.Intercept - (condition.1.Intercept + condition.trial.1_3.Intercept),
  diff_c1_t24 = condition.1.Intercept + condition.trial.1_2.Intercept - (condition.1.Intercept + condition.trial.1_4.Intercept),
  diff_c1_t34 = condition.1.Intercept + condition.trial.1_3.Intercept - (condition.1.Intercept + condition.trial.1_4.Intercept),

  diff_c2_t12 = condition.2.Intercept + condition.trial.2_1.Intercept - (condition.2.Intercept + condition.trial.2_2.Intercept),
  diff_c2_t13 = condition.2.Intercept + condition.trial.2_1.Intercept - (condition.2.Intercept + condition.trial.2_3.Intercept),
  diff_c2_t14 = condition.2.Intercept + condition.trial.2_1.Intercept - (condition.2.Intercept + condition.trial.2_4.Intercept),
  diff_c2_t23 = condition.2.Intercept + condition.trial.2_2.Intercept - (condition.2.Intercept + condition.trial.2_3.Intercept),
  diff_c2_t24 = condition.2.Intercept + condition.trial.2_2.Intercept - (condition.2.Intercept + condition.trial.2_4.Intercept),
  diff_c2_t34 = condition.2.Intercept + condition.trial.2_3.Intercept - (condition.2.Intercept + condition.trial.2_4.Intercept)
  )   %>% 
  select(starts_with("d")) 

# median_hdi takes median, lowerci and upperci for each column
cc_summary <- cc %>% summarise( across(everything(), median_hdi, .width=.95 ) )

# get probability of direction
cc_pd <- pd(cc)

# set cc properly and create tags in DD
CC <- data.frame()
for(i in c(1:length(cc))){
CC <- rbind(CC,(round(cc_summary[[i]][1:3],2) ) )
}
rownames(CC) <- colnames(cc_summary)
colnames(CC) <- c("median", "lowerCI95", "upperCI95")
tag <- CC$median %>% as.character()
DD <- CC %>% rownames_to_column() %>% 
  mutate(rowname = factor(rowname,colnames(cc_summary)),
         tag =  paste(median,"[",lowerCI95,",", upperCI95, "] --", round(cc_pd$pd,3)) )

# Errorbars
p2 <- DD %>% ggplot()+
  geom_errorbarh(aes(xmin=lowerCI95,xmax=upperCI95,y=rowname) ) +
  geom_point(aes(x=median,y=rowname)) +
#  geom_text(aes(x=.85,label=(tag), y=rowname),size=3) +
  #xlim(-.25,1) +
  theme_bw() +
  ylab("Contrasts") +
  xlab("Posterior distribution (median, ci-95%)")

# Table
p3 <- DD %>% ggplot()+
 # geom_errorbarh(aes(xmin=lowerCI95,xmax=upperCI95,y=rowname) ) +
  # geom_point(aes(x=median,y=rowname)) +
  geom_text(aes(x=.85,label=(tag), y=rowname),size=3) +
  #xlim(-.25,1) +
  theme_void() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        )
p <- (p2 + p3)

return(list(s,p))
}

```


