---
title: "04_Modelling_GUSO_MB16"
author: "ML"
date: "2022-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Modelling non-calibrated procustus and sparc and save
```{r modelling, eval=FALSE, include=FALSE}
load(file = "Data.RData")

# non-calibrated models 0M

# syntax
form0M_procustus <- bf(response0M_procustus ~ 0 + condition  +  (1 | condition:participant) + (1|condition:trial) )  
form0M_sparc <- bf(response0M_sparc         ~ 0 + condition  +  (1 | condition:participant) + (1|condition:trial) )  
form0M_procustus_d <- bf(response0M_procustus ~ 0 + condition  * difficulty_s + (1 + difficulty_s | condition:participant) + (1|condition:trial) )  
form0M_sparc_d <- bf(response0M_sparc         ~ 0 + condition  *  difficulty_s + (1 + difficulty_s| condition:participant) + (1|condition:trial) )  

# priors + modellingup
#prior0M <- get_prior( form0M_procustus , data = Data)
prior0M <- c(brms::prior(normal(0.5, .25), class = "b"))
model_procustus0M <- run_model_cmdstanr(Data,form0M_procustus,"skew_normal",prior0M)
prior0M <- c(brms::prior(normal(10, .25), class = "b"))
model_sparc0M <- run_model_cmdstanr(Data,form0M_sparc,"skew_normal",prior0M)
prior0M_d <- c(brms::prior(normal(0.5, .25), class = "b"))
model_procustus0M_d <- run_model_cmdstanr(Data,form0M_procustus_d,"skew_normal",prior0M_d)
prior0M_d <- c(brms::prior(normal(10, .25), class = "b"))
model_sparc0M_d <- run_model_cmdstanr(Data,form0M_sparc_d,"skew_normal",prior0M_d)

save(file = "Fit/model_procustus0M.RData", model_procustus0M)
save(file = "Fit/model_sparc0M.RData", model_sparc0M)
save(file = "Fit/model_procustus0M_d.RData", model_procustus0M_d)
save(file = "Fit/model_sparc0M_d.RData", model_sparc0M_d)

```

# Modelling calibrated procustus and sparc and save
```{r modelling, eval=FALSE, include=FALSE}
load(file = "Data.RData")

# syntax
form1M_procustus <- bf(response1M_procustus ~ 0 + condition  +  (1 | condition:participant) + (1|condition:trial) )  
form1M_sparc <- bf(response1M_sparc         ~ 0 + condition  +  (1 | condition:participant) + (1|condition:trial) )  
form1M_procustus_d <- bf(response1M_procustus ~ 0 + condition  * difficulty_s + (1 + difficulty_s | condition:participant) + (1|condition:trial) )  
form1M_sparc_d <- bf(response1M_sparc         ~ 0 + condition  *  difficulty_s + (1 + difficulty_s| condition:participant) + (1|condition:trial) )  

# priors + modelling
#prior0M <- get_prior( form0M_procustus , data = Data)
prior1M <- c(brms::prior(normal(0.5, .25), class = "b"))
model_procustus1M <- run_model_cmdstanr(Data,form1M_procustus,"skew_normal",prior1M)
prior1M <- c(brms::prior(normal(0.5, .25), class = "b"))
model_sparc1M <- run_model_cmdstanr(Data,form1M_sparc,"skew_normal",prior1M)
prior1M_d <- c(brms::prior(normal(0.5, .25), class = "b"))
model_procustus1M_d <- run_model_cmdstanr(Data,form1M_procustus_d,"skew_normal",prior1M_d)
prior1M_d <- c(brms::prior(normal(10, .25), class = "b"))
model_sparc1M_d <- run_model_cmdstanr(Data,form1M_sparc_d,"skew_normal",prior1M_d)

save(file = "Fit/model_procustus1M.RData", model_procustus1M)
save(file = "Fit/model_sparc1M.RData", model_sparc1M)
save(file = "Fit/model_procustus1M_d.RData", model_procustus1M_d)
save(file = "Fit/model_sparc1M_d.RData", model_sparc1M_d)

```

# multivariate model for procustus and sparc
```{r modelling, eval=FALSE, include=FALSE}
form0M_procustus <- bf(response0M_procustus ~ 0 + condition  +  (1 |A| condition:participant) + (1|B|condition:trial) )  
form0M_sparc <- bf(response0M_sparc         ~ 0 + condition  +  (1 |A| condition:participant) + (1|B|condition:trial) )  
form <- form0M_procustus + form0M_sparc
prior <- get_prior( form, data = Data)
model_1 <- run_model_cmdstanr(Data,form,"gaussian",prior)

save(file = "Fit/model_1.RData", model_1)

fit <- model_1
pp_check(fit,resp="response0Mprocustus")
pp_check(fit,resp="response0Msparc")


form0M_procustus <- bf(response0M_procustus ~ 0 + condition*difficulty_s  +  (1 + difficulty_s |A| condition:participant) + (1|B|condition:trial) )  
form0M_sparc <- bf(response0M_sparc         ~ 0 + condition*difficulty_s  +  (1 + difficulty_s |A| condition:participant) + (1|B|condition:trial) )  
form <- form0M_procustus + form0M_sparc
prior <- get_prior( form, data = Data)
model_2 <- run_model_cmdstanr(Data,form,"gaussian",prior)

save(file = "Fit/model_2.RData", model_2)

fit <- model_2
pp_check(fit,resp="response0Mprocustus")
pp_check(fit,resp="response0Msparc")

do_BF_comparison(model_1,model_2)
#Estimated log Bayes factor in favor of fit1 over fit2: 14.74015

```

# non-calibrated and calibrated procustus Questionnaires WQP MPQS MPQP Difficulty
```{r questionnaires, eval=FALSE, include=FALSE}
load("Data.RData")

prior0 <- c(brms::prior(normal(0, 3), class = "b"))
prior0M <- c(brms::prior(normal(0, 3), class = "b"), 
             brms::prior(normal(0, 3), class = "b", coef = "log_response0M_procustus"))
prior1M <- c(brms::prior(normal(0, 3), class = "b"), 
             brms::prior(normal(0, 3), class = "b", coef = "response1M_procustus"))

formH3 <-  bf(WPQ ~ 0 + condition   + (1  |  condition:participant + condition:trial) )
formH3response0M_procustus <- bf(WPQ ~ 0 + log_response0M_procustus * condition   +  (1  |  condition:participant + condition:trial))
formH3response1M_procustus <- bf(WPQ ~ 0 + response1M_procustus * condition   +  (1  |  condition:participant + condition:trial) )

modelH3_WPQ <- run_model_cmdstanr(Data,formH3,"gaussian",prior0)
modelH3response0M_WPQ <- run_model_cmdstanr(Data,formH3response0M_procustus,"gaussian",prior0M )
modelH3response1M_WPQ <- run_model_cmdstanr(Data,formH3response1M_procustus,"gaussian",prior1M )

formH3 <-  bf(MPQS ~ 0 + condition   + (1  |  condition:participant + condition:trial) )
formH3response0M_procustus <- bf(MPQS ~ 0 + log_response0M_procustus * condition +  (1  |  condition:participant + condition:trial))
formH3response1M_procustus <- bf(MPQS ~ 0 + response1M_procustus * condition +  (1  |  condition:participant + condition:trial) )

modelH3_MPQS <- run_model_cmdstanr(Data,formH3,"gaussian",prior0)
modelH3response0M_MPQS <- run_model_cmdstanr(Data,formH3response0M_procustus,"gaussian",prior0M )
modelH3response1M_MPQS <- run_model_cmdstanr(Data,formH3response1M_procustus,"gaussian",prior1M )

formH3 <-  bf(MPQP ~ 0 + condition   + (1  |  condition:participant + condition:trial) )
formH3response0M_procustus <- bf(MPQP ~ 0 + log_response0M_procustus * condition  +   (1  |  condition:participant + condition:trial))
formH3response1M_procustus <- bf(MPQP ~ 0 + response1M_procustus * condition  +   (1  |  condition:participant + condition:trial) )

modelH3_MPQP <- run_model_cmdstanr(Data,formH3,"gaussian",prior0)
modelH3response0M_MPQP <- run_model_cmdstanr(Data,formH3response0M_procustus,"gaussian",prior0M )
modelH3response1M_MPQP <- run_model_cmdstanr(Data,formH3response1M_procustus,"gaussian",prior1M )

formH3 <-  bf(Difficulty ~ 0 + condition + (1  |  condition:participant + condition:trial) )
formH3response0M_procustus <- bf(difficulty_s ~ 0 + log_response0M_procustus * condition  +  (1  |  condition:participant + condition:trial))
formH3response1M_procustus <- bf(difficulty_s ~ 0 + response1M_procustus * condition +  (1  |  condition:participant + condition:trial) )

modelH3_Difficulty <- run_model_cmdstanr(Data,formH3,"gaussian",prior0)
modelH3response0M_Difficulty <- run_model_cmdstanr(Data,formH3response0M_procustus,"gaussian",prior0M )
modelH3response1M_Difficulty <- run_model_cmdstanr(Data,formH3response1M_procustus,"gaussian",prior1M )

save(file = "Fit/modelH3_WPQ.RData",modelH3_WPQ)
save(file = "Fit/modelH3response0M_WPQ.RData",modelH3response0M_WPQ)
save(file = "Fit/modelH3response1M_WPQ.RData",modelH3response1M_WPQ)

save(file = "Fit/modelH3_MPQS.RData",modelH3_MPQS)
save(file = "Fit/modelH3response0M_MPQS.RData",modelH3response0M_MPQS)
save(file = "Fit/modelH3response1M_MPQS.RData",modelH3response1M_MPQS)

save(file = "Fit/modelH3_MPQP.RData",modelH3_MPQP)
save(file = "Fit/modelH3response0M_MPQP.RData",modelH3response0M_MPQP)
save(file = "Fit/modelH3response1M_MPQP.RData",modelH3response1M_MPQP)

save(file = "Fit/modelH3_Difficulty.RData",modelH3_Difficulty)
save(file = "Fit/modelH3response0M_Difficulty.RData",modelH3response0M_Difficulty)
save(file = "Fit/modelH3response1M_Difficulty.RData",modelH3response1M_Difficulty)


```

# Hypothesis 3: Multivariate model Questionnaires
```{r questionnaires, eval=FALSE, include=FALSE}
#save(file = "Results/modelH3response1M_MPQP.RData",modelH3response1M_WPQ)
# Multivariate basic model

formWPQ  <- bf(WPQ ~ 1 + condition + (1  | A | condition:participant) + (1 | B | condition:trial) )
formMPQS <- bf(MPQS ~ 1 + condition + (1 | A |  condition:participant) + (1 | B | condition:trial) )
formMPQP <- bf(MPQP ~ 1 + condition  + (1 | A |  condition:participant) + (1 | B | condition:trial) )
formMulti = formWPQ + formMPQS + formMPQP
modelH3_Multi_basic <- run_model_cmdstanr(Data,formMulti,"gaussian",prior0)

fit <- modelH3_Multi_basic

formWPQ  <- bf(WPQ ~ 1 + condition  * log_response0M_procustus + (1  | A | condition:participant) + (1 | B | condition:trial) )
formMPQS <- bf(MPQS ~ 1 + condition  * log_response0M_procustus + (1 | A |  condition:participant) + (1 | B | condition:trial) )
formMPQP <- bf(MPQP ~ 1 + condition   * log_response0M_procustus + (1 | A |  condition:participant) + (1 | B | condition:trial) )
formMulti = formWPQ + formMPQS + formMPQP
modelH3_Multi_metric <- run_model_cmdstanr(Data,formMulti,"gaussian",prior0)

fit <- modelH3_Multi_metric

### post_analysis_Multi_basic <- do_post_analysis_Multi(modelH3_Multi_basic) ## this throws an error WARNING!!!
hypothesis_testH3_Multi_basic_WPQ <- hypothesis(modelH3_Multi_basic,"b_WPQ_condition2 > 0", class = NULL)
hypothesis_testH3_Multi_basic_MPQS <- hypothesis(modelH3_Multi_basic,"b_MPQS_condition2 > 0", class = NULL)
hypothesis_testH3_Multi_basic_MPQP <- hypothesis(modelH3_Multi_basic,"b_MPQP_condition2 > 0 ", class = NULL)

### post_analysis_Multi_metric <- do_post_analysis_Multi(modelH3_Multi_metric) ## this throws an error WARNING!!!
hypothesis_testH3_Multi_metric_WPQ <- hypothesis(modelH3_Multi_metric,"b_WPQ_condition2:log_response0M_procustus + b_WPQ_condition2 > b_WPQ_log_response0M_procustus", class = NULL)
hypothesis_testH3_Multi_metric_MPQS <- hypothesis(modelH3_Multi_metric,"b_MPQS_condition2:log_response0M_procustus + b_MPQS_condition2 > b_MPQS_log_response0M_procustus", class = NULL)
hypothesis_testH3_Multi_metric_MPQP <- hypothesis(modelH3_Multi_metric,"b_MPQP_condition2:log_response0M_procustus + b_MPQP_condition2 > b_MPQP_log_response0M_procustus", class = NULL)
comparison_procustus_Multi_metric <- do_comparison(modelH3_Multi_basic,modelH3_Multi_metric)

save(file = "Results/modelH3_Multi_basic.RData", modelH3_Multi_basic)
save(file = "Results/modelH3_Multi_metric.RData", modelH3_Multi_metric)

### save(file = "Results/post_analysis_Multi_basic.RData", post_analysis_Multi_basic)
save(file = "Results/hypothesis_testH3_Multi_basic_WPQ.RData", hypothesis_testH3_Multi_basic_WPQ)
save(file = "Results/hypothesis_testH3_Multi_basic_MPQS.RData", hypothesis_testH3_Multi_basic_MPQS)
save(file = "Results/hypothesis_testH3_Multi_basic_MPQP.RData", hypothesis_testH3_Multi_basic_MPQP)


### save(file = "Results/post_analysis_Multi_metric.RData", post_analysis_Multi_metric)
save(file = "Results/hypothesis_testH3_Multi_metric_WPQ.RData", hypothesis_testH3_Multi_metric_WPQ)
save(file = "Results/hypothesis_testH3_Multi_metric_MPQS.RData", hypothesis_testH3_Multi_metric_MPQS)
save(file = "Results/hypothesis_testH3_Multi_metric_MPQP.RData", hypothesis_testH3_Multi_metric_MPQP)
save(file = "Results/comparison_procustus_Multi_metric.RData", comparison_procustus_Multi_metric)

```
